services:
  - type: web
    name: taxai-ca-saas
    env: python
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: GOOGLE_CLIENT_ID
        value: "716538344271-vgaduq0nsn6g4ip17fktsaloe9s3u59p.apps.googleusercontent.com"
      - key: DATABASE_URL
        value: "postgresql://postgres:sayexcusefirst2@db.simimchrlxtpfpygbetg.supabase.co:5432/postgres"
    startCommand: "gunicorn main:app"

    plan: free
